{{- if .Values.jmsCore.enabled }}
{{- with .Values.jmsCore }}
{{- $fullName := printf "%s-%s" (include "jumpserver.fullname" $) "jms-core" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "jumpserver.labels" $ | nindent 4 }}
    {{- toYaml .labels | nindent 4 }}
  {{- with .persistence.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
  {{- with .persistence.finalizers  }}
  finalizers:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .persistence.size | quote }}
  storageClassName: {{ .persistence.storageClassName }}
{{- end }}
{{- end }}