{{- if .Values.jmsGuacamole.enabled }}
{{- with .Values.jmsGuacamole }}
{{- $fullName := printf "%s-%s" (include "jumpserver.fullname" $) "jms-guacamole" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "jumpserver.labels" $ | nindent 4 }}
    {{- toYaml .labels | nindent 4 }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.web.port }}
      targetPort: web
      protocol: TCP
      name: web
  selector:
    app.kubernetes.io/name: {{ include "jumpserver.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    {{- toYaml .labels | nindent 4 }}
{{- end }}
{{- end }}